apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mariadb
  labels: &MariaDBDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: mariadb-server
data:
  host: mariadb-container
  name: lifo
  my.cnf: |-
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    datadir=/var/lib/mariadb
    port={{ .Values.service.port }}
    ignore_db_dirs=lost+found
    ssl-ca=/etc/mysql/mariadb.conf.d/certs/ca.crt
    ssl-cert=/etc/mysql/mariadb.conf.d/certs/tls.crt
    ssl-key=/etc/mysql/mariadb.conf.d/certs/tls.key
    